Update prompt

diff --git a/stow/.config/bash/prompt b/stow/.config/bash/prompt
--- a/stow/.config/bash/prompt
+++ b/stow/.config/bash/prompt
@@ -1,24 +1,8 @@
-# Highlight the user name when logged in as root.
-if [[ "${USER}" == "root" ]]; then
-    userStyle="${red}";
-else
-    userStyle="${orange}";
-fi;
-
-# Highlight the hostname when connected via SSH.
-if [[ "${SSH_TTY}" ]]; then
-    hostStyle="${bold}${red}";
-else
-    hostStyle="${yellow}";
-fi;
-
-# Set the terminal title and prompt.
-PS1='$([ $? == 0 ] && echo 😀 || echo 😱) '
+PS1=''
+PS1+='\[${white}\]\t' # current time
+PS1+=' $(s=$?; [ $s == 0 ] && echo "${reset}${s}" || echo "${red}${s}") ' # last command exit status
 PS1+="\[\033]0;\W\007\]"; # working directory base name
-PS1+="\[${userStyle}\]\u"; # username
-PS1+="\[${white}\]@";
-PS1+="\[${hostStyle}\]\h"; # host
-PS1+="\[${white}\]:";
+#PS1+="\[${white}\]:: ";
 PS1+="\[${green}\]\w"; # working directory full path
 PS1+="\[${yellow}\]\$(git_branch_read -wp)\[${reset}\]";
 PS1+=" \[${white}\]\$ \[${reset}\]"; # `$` (and reset color)
