WIP

diff --git a/stow/.config/bash/src/functions b/stow/.config/bash/src/functions
--- a/stow/.config/bash/src/functions
+++ b/stow/.config/bash/src/functions
@@ -1,7 +1,24 @@
-take() {
-  mkdir -p "$*" && cd "$_" || return 1
+wcd() {
+  if [ -z "$1" ]; then
+    echo "Usage: wcd <command>"
+    return 1
+  fi
+
+  local cmd_path
+  cmd_path="$(command -v "$1")" || {
+    echo "Command '$1' not found"
+    return 1
+  }
+
+  cd -- "$(dirname "$cmd_path")" || return 1
 }
 
-wcd() {
-  cd "$(dirname "$(command -v "$1")")" || return 1
+take() {
+  if [ -z "$1" ]; then
+    echo "Usage: take <directory_path>"
+    return 1
+  fi
+
+  mkdir -p -- "$1" && cd -- "$1" || return 1
 }
+
